# Generated by Django 2.2.3 on 2019-07-24 17:21

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('objects', myapp.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.Department'),
        ),
    ]
