# Generated by Django 2.2.3 on 2019-07-24 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190724_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employee_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
