# Generated by Django 2.2.3 on 2019-07-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('myapp', '0004_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='employee_type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Employee Type'),
        ),
    ]
