# Generated by Django 2.2.3 on 2019-07-24 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190724_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='myapp.Department'),
        ),
    ]
