# Generated by Django 2.2.3 on 2019-07-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190724_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='leaveType',
            new_name='leave_type',
        ),
    ]
