# Generated by Django 2.2.3 on 2019-07-25 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20190725_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaverequests', to=settings.AUTH_USER_MODEL),
        ),
    ]
